micronaut:
  application:
    name: allowance
  server:
    port: 8083
  netty:
    event-loops:
      other:
        num-threads: 10
        prefer-native-transport: true
  http:
    client:
      read-timeout: 300s
      max-content-length: 30MB
      event-loop-group: other
    services:
      gateway:
        urls:
          - ${ALLOWANCE_LOGIN_URL}
        pool:
          enabled:
            max-connections: 50
  security:
    token:
      jwt:
        signatures:
          secret:
            validation:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET}
---
r2dbc:
  datasources:
    default:
      dialect: MYSQL
      url: ${ALLOWANCE_R2DBC_URL}
      username: ${ALLOWANCE_JDBC_USER}
      password: ${ALLOWANCE_JDBC_PASSWORD}
#      url: ${BACKUP_ALLOWANCE_R2DBC_URL} # backup
datasources:
  default:
    dialect: MYSQL
    url: ${ALLOWANCE_JDBC_URL}
    username: ${ALLOWANCE_JDBC_USER}
    password: ${ALLOWANCE_JDBC_PASSWORD}
#    url: ${BACKUP_ALLOWANCE_JDBC_URL} # pushes the flyway schema
#    username: ${BACKUP_ALLOWANCE_JDBC_USER}
#    password: ${BACKUP_ALLOWANCE_JDBC_PASSWORD}
---
flyway:
  datasources:
    default:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3
---
allowance:
  service:
    credentials:
      username: ${ALLOWANCE_LOGIN_USERNAME} # login url is above in client stanza
      password: ${ALLOWANCE_LOGIN_PASSWORD}
---
backup:
  encryption:
    aes256GcmPassword: ${BACKUP_ALLOWANCE_AES_GCM_PASSWORD}