micronaut:
  application:
    name: allowance
  server:
    port: 8083
  netty:
    event-loops:
      other:
        num-threads: 10
        prefer-native-transport: true
  security:
    token:
      jwt:
        signatures:
          secret:
            validation:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET}
---
r2dbc:
  datasources:
    default:
      dialect: MYSQL
      url: ${ALLOWANCE_R2DBC_URL}
      username: ${ALLOWANCE_JDBC_USER}
      password: ${ALLOWANCE_JDBC_PASSWORD}
datasources:
  default:
    dialect: MYSQL
    url: ${ALLOWANCE_JDBC_URL}
    username: ${ALLOWANCE_JDBC_USER}
    password: ${ALLOWANCE_JDBC_PASSWORD}
---
flyway:
  datasources:
    default:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3
