ALTER TABLE allowance ADD SYSTEM VERSIONING;
ALTER TABLE task ADD SYSTEM VERSIONING;
ALTER TABLE tasktype ADD SYSTEM VERSIONING;
ALTER TABLE task_allowance ADD SYSTEM VERSIONING;
ALTER TABLE tasktype_allowance ADD SYSTEM VERSIONING;